name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository so we can run our tasks
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go (adjust the version as needed)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # Install Task (the Task runner from https://taskfile.dev)
      - name: Install Task
        run: |
          curl -sL https://taskfile.dev/install.sh | sh
          # Move the task binary into a directory in PATH
          sudo mv task /usr/local/bin/

      # Run the unit tests via Task (assumes a "test" task exists in your Taskfile)
      - name: Run Go Unit Tests
        run: task test

      # Run the linter via Task (assumes a "lint" task exists in your Taskfile)
      - name: Run Go Linter
        run: task lint
