name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: unit-tests
        run: |
              go test ./... -coverprofile=coverage.out
              cat coverage.out | grep -v "query/parser.gen.go" > coverage_filtered.out | grep -v "github.com/defer-panic/dumbql/query/ast.go:81"
              go tool cover -func=coverage_filtered.out

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.0
